JCC = javac

default: Obj_User.class RequiresRole.class Credential.class Session.class MVC_model_interface.class MVC_model.class  MarketServer.class \
View_login.class View_login_fail.class View_menu.class View_welcome.class View_browse_customer.class \
Interface_user.class Interface_command.class \
AuthorizationException.class AuthorizationInvocationHandler.class\
Factory_abstract.class Factory_concrete_admin.class Factory_concrete_customer.class Factory_admin.class Factory_customer.class Factory_producer.class \
Command_addAdmin.class Command_AddItem.class Command_browse_admin.class Command_browse_customer.class Command_loadCart.class Command_checkOut.class \
Command_RemoveItem.class Command_updateInfo_admin.class Command_updateInfo_customer.class Command_updateItem.class Command_viewOrder.class \
Control_menu.class Control_addAdmin.class Control_addItem.class Control_browse_admin.class Control_browse_customer.class Control_cart.class Control_checkOut.class \
Control_login.class Control_removeItem.class Control_updateInfo_admin.class Control_updateInfo_customer.class Control_viewOrder.class \
Controller_client.class \
Command_invoker.class Dispatcher.class FrontController.class MarketClient.class


Obj_User.class: Obj_User.java
	$(JCC) Obj_User.java

RequiresRole.class: RequiresRole.java
	$(JCC) RequiresRole.java
	
Credential.class: Credential.java
	$(JCC) Credential.java
		
Session.class: Session.java
	$(JCC) Session.java

MVC_model_interface.class: MVC_model_interface.java
	$(JCC) MVC_model_interface.java

MVC_model.class: MVC_model.java
	$(JCC) MVC_model.java

MarketServer.class: MarketServer.java
	$(JCC) MarketServer.java

View_login.class: View_login.java
	$(JCC) View_login.java

View_login_fail.class: View_login_fail.java
	$(JCC) View_login_fail.java

View_menu.class: View_menu.java
	$(JCC) View_menu.java

View_welcome.class: View_welcome.java
	$(JCC) View_welcome.java

View_browse_customer.class: View_browse_customer.java
	$(JCC) View_browse_customer.java

Interface_user.class: Interface_user.java
	$(JCC) Interface_user.java

Interface_command.class: Interface_command.java
	$(JCC) Interface_command.java

AuthorizationException.class: AuthorizationException.java
	$(JCC) AuthorizationException.java

AuthorizationInvocationHandler: AuthorizationInvocationHandler.java
	$(JCC) AuthorizationInvocationHandler.java
	
Factory_abstract.class: Factory_abstract.java
	$(JCC) Factory_abstract.java

Factory_concrete_admin.class: Factory_concrete_admin.java
	$(JCC) Factory_concrete_admin.java

Factory_concrete_customer.class: Factory_concrete_customer.java
	$(JCC) Factory_concrete_customer.java

Factory_admin.class: Factory_admin.java
	$(JCC) Factory_admin.java

Factory_customer.class: Factory_customer.java
	$(JCC) Factory_customer.java

Factory_producer.class: Factory_producer.java
	$(JCC) Factory_producer.java

Command_addAdmin.class: Command_addAdmin.java
	$(JCC) Command_addAdmin.java
	
Command_AddItem.class: Command_AddItem.java
	$(JCC) Command_AddItem.java

Command_browse_admin.class: Command_browse_admin.java
	$(JCC) Command_browse_admin.java
	
Command_browse_customer.class: Command_browse_customer.java
	$(JCC) Command_browse_customer.java

Command_loadCart.class: Command_loadCart.java
	$(JCC) Command_loadCart.java
	
Command_checkOut.class: Command_checkOut.java
	$(JCC) Command_checkOut.java

Command_RemoveItem.class: Command_RemoveItem.java
	$(JCC) Command_RemoveItem.java
	
Command_updateInfo_admin.class: Command_updateInfo_admin.java
	$(JCC) Command_updateInfo_admin.java

Command_updateInfo_customer.class: Command_updateInfo_customer.java
	$(JCC) Command_updateInfo_customer.java
	
Command_updateItem.class: Command_updateItem.java
	$(JCC) Command_updateItem.java

Command_viewOrder.class: Command_viewOrder.java
	$(JCC) Command_viewOrder.java

Control_menu.class: Control_menu.java
	$(JCC) Control_menu.java
	
Control_addAdmin.class: Control_addAdmin.java
	$(JCC) Control_addAdmin.java

Control_addItem.class: Control_addItem.java
	$(JCC) Control_addItem.java

Control_browse_admin.class: Control_browse_admin.java
	$(JCC) Control_browse_admin.java

Control_browse_customer.class: Control_browse_customer.java
	$(JCC) Control_browse_customer.java

Control_cart.class: Control_cart.java
	$(JCC) Control_cart.java

Control_checkOut.class: Control_checkOut.java
	$(JCC) Control_checkOut.java

Control_login.class: Control_login.java
	$(JCC) Control_login.java

Control_removeItem.class: Control_removeItem.java
	$(JCC) Control_removeItem.java

Control_updateInfo_admin.class: Control_updateInfo_admin.java
	$(JCC) Control_updateInfo_admin.java

Control_updateInfo_customer.class: Control_updateInfo_customer.java
	$(JCC) Control_updateInfo_customer.java

Control_viewOrder.class: Control_viewOrder.java
	$(JCC) Control_viewOrder.java

Controller_client: Controller_client.java
	$(JCC) Controller_client.java
	
Command_invoker.class: Command_invoker.java
	$(JCC) Command_invoker.java

Dispatcher.class: Dispatcher.java
	$(JCC) Dispatcher.java

FrontController.class: FrontController.java
	$(JCC) FrontController.java	

MarketClient.class: MarketClient.java
	$(JCC) MarketClient.java

clean:
	$(RM) *.class
